import { useState } from "react";
import { cardId } from "../../../games/commercial-hub/cards";
import { CITY_CONDITIONS, SUIT_NAMES } from "../../../games/commercial-hub/data";
import type { HubClientAction } from "../../../games/commercial-hub/state";
import { SUITS } from "../../../games/commercial-hub/types";
import type { HubView } from "../../../games/commercial-hub/view";
import type { ClientRoomMessageInput, RoomPublicState } from "../../../shared/room-protocol";
import type { RoomConnectionState } from "../../lib/room-socket";
import { CityBoard, type MapHighlight } from "./CityBoard";
import { OpeningRewards } from "./OpeningRewards";
import { IncomePanel } from "./IncomePanel";
import { InvestmentPanel } from "./InvestmentPanel";
import { ProcurementPanel } from "./ProcurementPanel";
import { eventText, PHASE_NAMES, PLAYER_COLORS, RESOURCE_NAMES, TIE_NAMES } from "./labels";
import { SuitMark } from "./SuitMark";
import "./commercial-hub.css";
interface Props { room: RoomPublicState; view: HubView; phaseVersion: number; send: (message: ClientRoomMessageInput) => void; connectionState: RoomConnectionState; pending: boolean; error: string | null }
export function CommercialHubScreen({ room, view, phaseVersion, send, connectionState, pending, error }: Props) {
  const [tab, setTab] = useState("turn"), [highlight, setHighlight] = useState<MapHighlight>({ district: null, suit: null });
  const name = (id: string) => `${view.players.indexOf(id) + 1}. ${room.players.find((p) => p.playerId === id)?.displayName ?? "商会"}`;
  const act = (action: HubClientAction) => send({ type: "GAME_ACTION", action, phaseVersion });
  const disconnected = connectionState !== "CONNECTED", self = view.companies.find((c) => c.playerId === view.playerId)!;
  const actionProps = { view, act, name }, final = view.round === view.finalRound;
  const hand = [...view.hand].sort((a, b) => SUITS.indexOf(a.suit) - SUITS.indexOf(b.suit) || a.rank - b.rank);
  const isHost = room.players.find((p) => p.playerId === view.playerId)?.isHost;
  const settlement = view.settlement;
  return <div className="hub" data-game-id="commercial-hub" data-phase={view.phase}>
    <header className="hub-heading"><div><span className="eyebrow">商都開発 · v{view.rulesVersion} · ROOM {room.roomCode}</span><h1>Round {view.round} <span>{PHASE_NAMES[view.phase]}</span></h1></div><a href="/#/rules/commercial-hub" target="_blank" rel="noreferrer">ルール ↗</a></header>
    <div className="hub-sticky-status">{final && <div className="hub-final-round" role="status">最終ラウンド · このラウンドの精算後に順位確定</div>}<div className="hub-overview"><strong>R{view.round} · 都市 Lv{view.cityLevel}<small>発展 {view.cityDevelopment} / {view.cityLevel < 4 ? [0, 14, 28, 44][view.cityLevel] : "到達"}</small><progress aria-label="都市発展" value={Math.min(44, view.cityDevelopment)} max={44}/></strong><span>{view.cityCondition.name}<small>切札：{view.trump ? SUIT_NAMES[view.trump] : "ノートランプ"}</small></span><span>{view.phase === "INVESTMENT" ? `投資 ${view.currentInvestmentPass}周目` : PHASE_NAMES[view.phase]}<small>{view.currentPlayer ? `${name(view.currentPlayer)}の手番` : "4人同時・全員確認"}</small></span></div></div>
    {view.finalRound < 10 && !final && <p className="hub-announcement">次のRound {view.finalRound}が最終ラウンドです</p>}
    <div className="hub-company-strip" aria-label="4商会の公開資源">{view.companies.map((c, i) => <article key={c.playerId} style={{ borderColor: PLAYER_COLORS[i] }}><strong>{name(c.playerId)}{c.playerId === view.playerId && "（自分）"}</strong><span>資金 {c.resources.cash} / 資材 {c.resources.materials} / 商品 {c.resources.goods}</span><small>手札{view.handCounts.find((h) => h.playerId === c.playerId)!.count}枚 · {view.connections[c.playerId]?.bot ? "BOT代行中" : view.connections[c.playerId]?.connected ? "接続中" : "切断中・60秒でBOT"}</small></article>)}</div>
    <div className="hub-my-finances" aria-label="自分の精算見込み"><span>現在資金 <b>{self.resources.cash}</b></span><span>未精算輸送費 <b>−{view.ownBalance.expense}</b></span><span>未精算通行料 <b>＋{view.ownBalance.income}</b></span><span>精算後見込 <b>{view.ownBalance.projectedCash}</b></span><span>暫定企業価値 <b>{view.ownValue.total}</b></span><small>企業価値は本人だけに表示。未精算費用は精算後に反映されます。</small></div>
    {disconnected && <div className="error-box" role="status">{connectionState === "OFFLINE" ? "オフラインです。" : "再接続しています。"}接続が戻ると現在の状態を復元します。60秒後はBOTが代行します。</div>}{error && <div className="error-box" role="alert">{error}</div>}
    <nav className="hub-mobile-tabs" aria-label="ゲーム画面">{[["turn", "手番"], ["city", "都市"], ["log", "履歴"]].map(([key, label]) => <button key={key} aria-pressed={tab === key} onClick={() => { setTab(key!); window.scrollTo({ top: 0, behavior: "instant" }); }}>{label}</button>)}</nav>
    {view.result && <section className="hub-card hub-result" aria-label="最終結果"><span className="eyebrow">FINAL RESULT</span><h2>{view.result.winners.map(name).join(" ＆ ")} の勝利</h2><p>{view.result.reason === "ROUND_10" ? "10ラウンド終了" : "Lv4到達翌ラウンド終了"} · 最終輸送費を精算済み</p><p>非赤字を優先 → 企業価値 → 事業資産 → 建物 → 公共事業。すべて同じなら同順位。</p><div className="hub-result-grid">{view.result.ranking.map((e) => <article key={e.playerId}><h3>{e.rank}位 {name(e.playerId)}</h3><strong>{e.value.total}点</strong>{e.deficit && <b className="hub-deficit">最終精算後：赤字（資金{e.cash}）</b>}<dl>{([["建物", e.value.buildings], ["輸送路", e.value.routes], ["公共事業", e.value.projects], ["資金", e.value.cash], ["資材・商品", e.value.inventory]] as const).map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><small>隣接順位との比較：{TIE_NAMES[e.tieBreak]}</small></article>)}</div>{isHost ? <button className="primary-button" disabled={pending || disconnected || room.players.some((p) => p.connectionStatus !== "CONNECTED")} onClick={() => send({ type: "REMATCH" })}>再戦</button> : <p>ホストの再戦操作を待っています。</p>}<small>席を維持し、開始プレイヤーを再抽選します。全員の再接続後に再戦できます。</small></section>}
    <div className="hub-layout"><main className={`hub-turn-column ${tab === "turn" ? "hub-visible" : ""}`}>
      <section className="hub-card hub-opportunities"><h2>今ラウンドの全商機</h2><ol>{view.opportunities.map((o, i) => <li key={i} className={i === view.trickIndex && ["TRICK", "REWARD", "TRICK_RESULT", "ROUND_START"].includes(view.phase) ? "current" : i < view.trickIndex ? "past" : ""}><SuitMark suit={o.suit} size={18}/><b>{i + 1}. {o.name}</b><small>{o.trump ? `${SUIT_NAMES[o.trump]}切札` : "ノートランプ"}</small></li>)}</ol>{view.round === 1 && <details><summary>開業商機の報酬を見る</summary><OpeningRewards/></details>}{view.cityCondition.id === "credit-crunch" && <p className="hub-announcement">信用収縮：カード順位は通常どおり。報酬は4位→1位、3位→2位、2位→3位、1位→4位。</p>}<details><summary>通常相場の袋</summary><p>使用済み：{view.marketUsed.map((id) => CITY_CONDITIONS.find((c) => c.id === id)!.name).join(" / ") || "なし"}</p><p>残候補：{view.marketRemaining.map((id) => CITY_CONDITIONS.find((c) => c.id === id)!.name).join(" / ") || "次の通常Rで5種類を補充"}</p></details></section>
      {view.phase !== "FINISHED" && <section className="hub-card hub-action-panel" aria-label="現在の操作"><div className="hub-section-title"><h2>{PHASE_NAMES[view.phase]}</h2>{pending && <small role="status">送信中…</small>}</div>{view.phase === "INVESTMENT" && <p className="hub-order">第{view.currentInvestmentPass}周 / {view.investmentOrder.map(name).join(" → ")}</p>}
        <fieldset className="hub-controls" disabled={pending || disconnected} key={`${view.round}:${view.phase}`}>
          {view.phase === "ROUND_START" && <><p>{view.round === 1 ? "開始プレイヤーを抽選しました。6商機のうち1回だけノートランプです。" : "商機の順番を見て、使うカードを考えましょう。"}</p><p>リード：{name(view.trickLeader)}。勝者に関係なく席順で交代します。</p><button className="primary-button" disabled={view.roundReady.includes(view.playerId)} onClick={() => act({ type: "ROUND_READY" })}>{view.roundReady.includes(view.playerId) ? "他の商会を待っています" : "商機を確認・準備OK"}</button><small>{view.roundReady.length}/4人確認</small></>}
          {view.phase === "TRICK" && <p className="hub-callout">{view.currentPlayer === view.playerId ? "あなたの手番です。手札から1枚選んでください。" : `${name(view.currentPlayer!)}のカードを待っています。`}<br/>リード：{view.playedCards[0] ? SUIT_NAMES[view.playedCards[0].card.suit] : "最初のカードで決定"}</p>}
          {view.phase === "REWARD" && (view.rewardChoice ? <><p>商機はトリック直後に使用します。使わなかった分は失効します。</p><div className="hub-buttons">{Array.from({ length: view.rewardChoice.maximum + 1 }, (_, n) => <button key={n} className="secondary-button" onClick={() => act({ type: "CLAIM_REWARD", amount: n })}>{n === 0 ? "使用しない" : view.rewardChoice!.kind === "SALE" ? `商品${n} → 資金${n * view.rewardChoice!.cash}` : view.rewardChoice!.kind === "PROCESS" ? `資材1 → 商品${view.rewardChoice!.goods}` : `資金${view.rewardChoice!.cash} → 資材1`}</button>)}</div></> : <p>{name(view.currentPlayer!)}の商機選択を待っています。</p>)}
          {view.phase === "TRICK_RESULT" && <><p>{view.trickResults.at(-1)?.ranking.map((p, i) => `${i + 1}位 ${name(p)}`).join(" / ")}</p><small>自動で次へ進みます。結果は履歴に残ります。</small></>}
          {view.phase === "PROCUREMENT" && <ProcurementPanel {...actionProps}/>}{view.phase === "PRODUCTION" && <IncomePanel {...actionProps}/>}{view.phase === "INVESTMENT" && <InvestmentPanel {...actionProps} highlight={setHighlight}/>}
          {view.phase === "ROUND_END" && <><p>下の精算結果を確認してください。</p><button className="primary-button" disabled={view.roundReady.includes(view.playerId)} onClick={() => act({ type: "ROUND_END_READY" })}>{view.roundReady.includes(view.playerId) ? "他の商会を待っています" : "精算を確認・次ラウンドへ"}</button><small>{view.roundReady.length}/4人確認</small></>}
        </fieldset>
      </section>}
      {["TRICK", "REWARD", "TRICK_RESULT"].includes(view.phase) && <section className="hub-card"><h2>場のカード</h2><div className="hub-played">{view.players.map((id) => { const c = view.playedCards.find((p) => p.playerId === id)?.card; return <div key={id}><small>{name(id)}{view.trickLeader === id ? " / Lead" : ""}</small>{c ? <strong><SuitMark suit={c.suit}/>{SUIT_NAMES[c.suit]} {c.rank}</strong> : <span>未提出</span>}</div>; })}</div></section>}
      {view.hand.length > 0 && <section className="hub-card hub-hand" aria-label="自分の手札"><h2>自分の手札 <small>本人だけに表示</small></h2><p className="hub-hint">Must Follow：リードスートを持っている場合は必ず従います。</p><div className="hub-hand-cards">{hand.map((c) => <button className={`hub-playing-card hub-suit-${c.suit}`} key={cardId(c)} aria-label={`${SUIT_NAMES[c.suit]} ${c.rank}`} disabled={pending || disconnected || !view.legalCards.some((a) => cardId(a) === cardId(c))} onClick={() => act({ type: "PLAY_CARD", card: c })}><SuitMark suit={c.suit}/><span>{SUIT_NAMES[c.suit]}</span><strong>{c.rank}</strong></button>)}</div></section>}
      {settlement && (view.phase === "ROUND_END" || view.phase === "FINISHED") && <section className="hub-card hub-settlement" aria-label="ラウンド精算"><h2>Round {settlement.round} 精算</h2><h3>自分の輸送費</h3><p>公共輸送 −{settlement.charges.filter((c) => c.payer === view.playerId && c.payee === null).reduce((n, c) => n + c.amount, 0)}</p>{view.players.filter((p) => p !== view.playerId).map((p) => <p key={p}>{name(p)}へ −{settlement.charges.filter((c) => c.payer === view.playerId && c.payee === p).reduce((n, c) => n + c.amount, 0)} / 受取 ＋{settlement.charges.filter((c) => c.payer === p && c.payee === view.playerId).reduce((n, c) => n + c.amount, 0)}</p>)}<strong>精算前 資金{settlement.cashBefore[view.playerId]} → 精算後 資金{settlement.cashAfter[view.playerId]}</strong><h3>都市発展</h3><p>建物 ＋{settlement.development.buildings} / 上位化 ＋{settlement.development.upgrades} / 輸送路 ＋{settlement.development.routes} / 公共事業 ＋{settlement.development.projects}</p><strong>{settlement.developmentBefore} → {settlement.developmentAfter}（＋{settlement.developmentAfter - settlement.developmentBefore}） / Lv{settlement.levelBefore} → Lv{settlement.levelAfter}</strong>{settlement.levelAfter > settlement.levelBefore && <p className="hub-announcement">{settlement.levelAfter === 2 ? "次Rから外周地区解放" : settlement.levelAfter === 3 ? "次Rは特別消費ブーム・在庫処分解放" : "次Rが最終ラウンド"}</p>}</section>}
    </main>
    <aside className={`hub-city-column ${tab === "city" ? "hub-visible" : ""}`}><CityBoard view={view} name={name} highlight={highlight}/><section className="hub-card" aria-label="公共事業"><h2>公共事業</h2><p>完成時に拠出1枠につき資金1を即時還元。都市発展＋5。</p>{view.publicProjects.map((p) => <article className="hub-project" key={p.id}><h3>{p.name} <small>{p.slots.filter((s) => s.playerId).length}/6枠{p.slots.every((s) => s.playerId) && " 完成"}</small></h3><div className="hub-project-slots">{p.slots.map((s, i) => <div key={i} className={s.playerId ? "filled" : ""} style={{ borderColor: s.playerId ? PLAYER_COLORS[view.players.indexOf(s.playerId)] : undefined }}><strong>{RESOURCE_NAMES[s.resource]}{s.resource === "cash" ? 2 : 1}</strong><small>{s.playerId ? name(s.playerId) : "空き"}</small></div>)}</div></article>)}<small>完成案件のみ1枠1点。単独最多＋1。同数最多ボーナスなし。</small></section></aside>
    <section className={`hub-log-column ${tab === "log" ? "hub-visible" : ""}`}><div className="hub-card"><h2>確定行動ログ</h2><small>新しい順。再接続後もサーバーの履歴を復元します。</small><ol className="hub-event-log">{[...view.events].reverse().map((e) => <li key={e.seq}><small>R{e.round} · #{e.seq}</small><span>{eventText(e, name)}</span></li>)}</ol></div></section></div>
  </div>;
}
