import { describe,expect,it } from "vitest";
import { createHubState,reduceHubState } from "../../../src/games/commercial-hub/engine";
import { SeededRandom } from "../../../src/games/pon-inai/random";
import { activeMajor,beginMajorEconomy,beginMajorInvestment,buyMajor,chooseMajor,majorChoiceOptions,nextProjects,type MajorCard } from "../../../src/games/commercial-hub/next-rules";
import { quoteInvestment } from "../../../src/games/commercial-hub/investment";
import { quoteBuildingUse } from "../../../src/games/commercial-hub/income";
import { accessOptions } from "../../../src/games/commercial-hub/logistics";
import { companyValue } from "../../../src/games/commercial-hub/scoring";
import { buildHubView } from "../../../src/games/commercial-hub/view";
import { assertCanBuild } from "../../../src/games/commercial-hub/buildings";
import { parseHubAction } from "../../../src/games/commercial-hub/web-actions";
import { candidateFinalRound } from "../../../src/games/commercial-hub/next-data";
import { publicArchive,createArchive } from "../../../src/server/lib/hub-archive";
import type { HubState,HubClientAction } from "../../../src/games/commercial-hub/state";
const players=["a","b","c","d"];
function fresh(auditor=true){const s=createHubState("trial",players,new SeededRandom(54),{trickRule:"NORMAL",auditor,rulesVariant:"NEXT",horizon:"11-13",majorInvestments:true});s.companies.forEach(c=>c.resources={cash:50,materials:20,goods:20});return s;}
function card(s:HubState,id:string,owner="a",activeRound=2){const c:MajorCard={id,owner,purchasedRound:activeRound-1,activeRound,status:"ACTIVE"};s.next!.cards.push(c);return c;}
function action(s:HubState,a:HubClientAction,p="a"){return reduceHubState(s,{...a,playerId:p},new SeededRandom(5));}
function select(s:HubState,id:string){s.next!.queue=[id];s.next!.returnPhase="PROCUREMENT";s.phase="MAJOR_SELECTION";}
describe("NEXT trial real Core boundaries",()=>{
 it("keeps formal defaults and RNG separate from major market settings",()=>{const old=createHubState("o",players,new SeededRandom(54));expect(old.rulesVersion).toBe("0.5");expect(old.next).toBeUndefined();expect(old.publicProjects).toHaveLength(2);const a=fresh();const b=createHubState("b",players,new SeededRandom(54),{trickRule:"NORMAL",auditor:true,rulesVariant:"NEXT",majorInvestments:false});expect(a.playerHands).toEqual(b.playerHands);expect(a.publicProjects).toHaveLength(5);expect(a.publicProjects.every(p=>p.availableRound===999)).toBe(true);});
 it("charges composite slot once, discounts materials only and respects priority",()=>{const s=fresh();s.round=5;s.cityLevel=3;s.phase="INVESTMENT";s.currentInvestmentPlayer="a";const hall=s.publicProjects.find(p=>p.id==="city-hall")!;hall.availableRound=5;expect(quoteInvestment(s,"a",{type:"CONTRIBUTE",projectId:hall.id,slot:5,benefit:"NONE"}).cost).toEqual({cash:0,materials:1,goods:1});s.benefits.a!.project=["DISCOUNT"];expect(quoteInvestment(s,"a",{type:"CONTRIBUTE",projectId:hall.id,slot:5,benefit:"DISCOUNT"}).cost).toEqual({cash:0,materials:0,goods:1});const after=action(s,{type:"CONTRIBUTE",projectId:hall.id,slot:5,benefit:"NONE"});expect(after.companies[0]!.resources.materials).toBe(19);expect(after.companies[0]!.resources.goods).toBe(19);expect(()=>quoteInvestment(after,"b",{type:"CONTRIBUTE",projectId:hall.id,slot:5,benefit:"NONE"})).toThrow();const priority=card(s,"public-works-priority","b");priority.project=hall.id;expect(()=>quoteInvestment(s,"a",{type:"CONTRIBUTE",projectId:hall.id,slot:5,benefit:"DISCOUNT"})).toThrow();});
 it("unlocks projects only on the following round and updates A/B horizons in engine",()=>{for(const horizon of ["11-13","12-14"] as const){const s=fresh();s.config.horizon=horizon;s.round=8;s.phase="INVESTMENT";s.currentInvestmentPass=2;s.investmentTurnIndex=3;s.currentInvestmentPlayer="a";s.cityLevel=3;s.cityDevelopment=64;const after=action(s,{type:"PASS_INVESTMENT"});expect(after.finalRound).toBe(candidateFinalRound(8,horizon));expect(after.publicProjects.find(p=>p.id==="central-tower")!.availableRound).toBe(9);expect(()=>quoteInvestment(after,"a",{type:"CONTRIBUTE",projectId:"central-tower",slot:0,benefit:"NONE"})).toThrow();}});
 it("has 21 map slots, only administrative multiple ownership, upgrade4/discount1 and cap7",()=>{const s=fresh();s.cityLevel=2;expect(()=>assertCanBuild([{id:"1",playerId:"a",district:"REDEVELOPMENT",suit:"industry",upgraded:false}],"a","REDEVELOPMENT","commerce",2,true)).not.toThrow();expect(()=>assertCanBuild([{id:"1",playerId:"a",district:"MARKET",suit:"commerce",upgraded:false}],"a","MARKET","commerce",2,true)).toThrow();s.buildings=[{id:"1",playerId:"a",district:"BUSINESS",suit:"commerce",upgraded:false}];expect(quoteInvestment(s,"a",{type:"UPGRADE",buildingId:"1",access:"PUBLIC"})).toMatchObject({baseCash:4,districtDiscount:1});s.buildings=Array.from({length:6},(_,i)=>({id:String(i),playerId:"a",district:i<3?"WORKSHOP":"MARKET",suit:i<3?"industry":"commerce",upgraded:false}));expect(()=>quoteInvestment(s,"a",{type:"BUILD",district:"WAREHOUSE",suit:"procurement"})).toThrow();s.round=2;card(s,"business-expansion");expect(()=>quoteInvestment(s,"a",{type:"BUILD",district:"WAREHOUSE",suit:"procurement"})).not.toThrow();});
 it("removes cash score without changing inventory or formal scoring",()=>{const s=fresh();const c=s.companies[0]!;expect(companyValue(c,[],[],[],undefined,true)).toMatchObject({cash:0,inventory:10});expect(companyValue(c,[],[],[]).cash).toBe(8);});
 it("buys one card with a delayed effect, refills same category, rejects final round and spoofed purchase",()=>{const s=fresh();s.cityLevel=3;s.round=4;s.phase="INVESTMENT";s.currentInvestmentPlayer="a";s.next!.market=["industry-modernization",null,"industrial-subsidy"];const after=action(s,{type:"BUY_MAJOR",cardId:"industry-modernization",suit:"commerce"});expect(after.companies[0]!.resources.cash).toBe(42);expect(after.next!.market[2]).toBe("industrial-subsidy");expect(activeMajor(after,"a","industry-modernization")).toBeUndefined();expect(after.currentInvestmentPlayer).not.toBe("a");s.round=s.finalRound;expect(()=>buyMajor(s,"a",{type:"BUY_MAJOR",cardId:"industry-modernization",suit:"commerce"})).toThrow();expect(()=>parseHubAction({type:"CHOOSE_MAJOR",cardId:"x",playerId:"b"},"a")).toThrow();expect(fresh(false).next!.permanentDeck).not.toContain("audit-contractor");});
 it("free build is a separate choice, no investment consumed, remains unavailable in prior production",()=>{const s=fresh();s.round=2;const c=card(s,"business-expansion");beginMajorInvestment(s);expect(s.phase).toBe("MAJOR_SELECTION");chooseMajor(s,"a",majorChoiceOptions(s)[0]!);expect(s.buildings).toHaveLength(1);expect(c.freeBuilt).toBe(true);expect(s.currentInvestmentPass).toBe(1);expect(s.currentInvestmentPlayer).toBe(s.investmentStarter);});
 it("modernization stacks with one additional upper use, royalty consumes normal only and transfers output",()=>{const s=fresh();s.round=2;s.phase="PRODUCTION";s.buildings=[{id:"upper",playerId:"b",district:"WORKSHOP",suit:"industry",upgraded:true}];card(s,"advanced-equipment","b");card(s,"industry-modernization","b").suit="industry";expect(quoteBuildingUse(s,"b","upper",1,"PUBLIC").reward.goods).toBe(4);card(s,"technology-royalty");select(s,"technology-royalty");const choice=majorChoiceOptions(s).find(a=>a.access==="PUBLIC"&&a.amount===1)!;chooseMajor(s,"a",choice);expect(s.companies[0]!.resources.goods).toBe(24);expect(s.companies[1]!.resources.materials).toBe(19);expect(s.usage.b!.buildings).toEqual(["upper"]);s.phase="PRODUCTION";const after=action(s,{type:"USE_BUILDING",buildingId:"upper",amount:1,access:"PUBLIC"},"b");expect(after.next!.extraUsed).toEqual(["b"]);expect(()=>quoteBuildingUse(after,"b","upper",1,"PUBLIC")).toThrow();});
 it("audit contractor receives others fees only",()=>{const s=fresh();s.round=2;s.phase="PRODUCTION";s.auditor.target="industry";s.buildings=[{id:"b",playerId:"b",district:"WORKSHOP",suit:"industry",upgraded:false},{id:"a",playerId:"a",district:"WORKSHOP",suit:"industry",upgraded:false}];card(s,"audit-contractor");const after=action(s,{type:"USE_BUILDING",buildingId:"b",amount:1,access:"PUBLIC"},"b");expect(after.companies[0]!.resources.cash).toBe(51);const own=action(after,{type:"USE_BUILDING",buildingId:"a",amount:1,access:"PUBLIC"});expect(own.companies[0]!.resources.cash).toBe(50);});
 it("blockade overrides monopoly and does not block public roads",()=>{const s=fresh();s.round=2;s.routes=[{playerId:"b",district:"WORKSHOP"},{playerId:"a",district:"WORKSHOP"}];card(s,"logistics-monopoly","b").district="WORKSHOP";expect(accessOptions(s,"a","WORKSHOP")).toEqual(["b"]);s.next!.blocked=["b"];expect(accessOptions(s,"a","WORKSHOP")).toEqual(["OWN","PUBLIC"]);expect(accessOptions(s,"b","WORKSHOP")).toEqual(["a","PUBLIC"]);});
 it("acquisition compares lifetime contributions and transfers unfinished ownership without refund",()=>{const s=fresh();s.round=2;const p=s.publicProjects[0]!;p.slots[0]!.playerId="b";p.slots[1]!.playerId="b";card(s,"public-works-acquisition");select(s,"public-works-acquisition");const before=structuredClone(s.companies);chooseMajor(s,"a",majorChoiceOptions(s)[0]!);expect(p.slots[0]!.playerId).toBe("a");expect(s.companies).toEqual(before);expect(s.next!.cards[0]!.status).toBe("USED");});
 it("subsidy snapshots eligible opponents, sums all capability uses with no cap and fizzles with no target",()=>{const s=fresh();s.round=2;s.buildings=Array.from({length:4},(_,i)=>({id:String(i),playerId:"b",district:"WORKSHOP",suit:"industry",upgraded:false}));const c=card(s,"industrial-subsidy");beginMajorEconomy(s);s.usage.b!.buildings=Array.from({length:12},()=>"used");beginMajorInvestment(s);expect(s.companies[0]!.resources.cash).toBe(62);expect(c.status).toBe("USED");const empty=fresh();empty.round=2;card(empty,"technology-royalty");beginMajorEconomy(empty);expect(empty.phase).toBe("PROCUREMENT");expect(empty.next!.cards[0]!.status).toBe("FIZZLED");});
 it("priority cannot repeat a project and neither views nor public archive expose next decks or hands",()=>{const s=fresh();s.round=2;const c=card(s,"public-works-priority");s.publicProjects[0]!.availableRound=1;c.project="market";beginMajorInvestment(s);expect(c.previousProject).toBe("market");expect(majorChoiceOptions(s).some(a=>a.projectId==="market")).toBe(false);const v=buildHubView(s,"a");expect(v.next).not.toHaveProperty("permanentDeck");const archive=JSON.stringify(publicArchive(s,createArchive(s,"ROOM",0)));expect(archive).not.toMatch(/playerHands|permanentDeck|counterDeck|npcDecision/);});
});
